name: Update Podcast Database
on:
  schedule:
    - cron: '0 */2 * * *' # רץ כל שעתיים
  workflow_dispatch: # מאפשר להריץ ידנית דרך לשונית Actions

# השורה הזו תעלים את אזהרת ה-Node.js המעצבנת בלוגים של גיטהאב
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    # הוספת הרשאות כתיבה לבוט
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update_database.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add database.json
          # ביצוע Commit רק אם יש שינויים בקובץ
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update database.json" && git push)
